"""add_nullable_local_time_and_timezone_to_availability_slots

Revision ID: 8a7979edb259
Revises: a20250910_meetup_cols
Create Date: 2025-09-12 11:01:16.668732

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a7979edb259'
down_revision: Union[str, Sequence[str], None] = '20250101_create_initial_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Columns already created in initial migration
    pass


def downgrade() -> None:
    # Columns will be dropped by initial migration downgrade
    op.drop_index('idx_meetup_proposer_user_id', table_name='meetup')
    op.alter_column('profile', 'live_tz',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('profile', 'languages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'languages',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('profile', 'live_tz',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index('idx_meetup_proposer_user_id', 'meetup', ['proposer_user_id'], unique=False)
    op.create_index('idx_meetup_confirmer_user_id', 'meetup', ['confirmer_user_id'], unique=False)
    op.alter_column('match', 'comment',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('availabilityslot', 'timezone')
    op.drop_column('availabilityslot', 'end_dt_local')
    op.drop_column('availabilityslot', 'start_dt_local')
    # ### end Alembic commands ###
