from __future__ import annotations

from typing import Dict


SUPPORTED_EMAIL_LANGS = {
    "en", "bg", "cs", "da", "de", "el", "es", "et", "fi", "fr", "ga",
    "hr", "hu", "it", "lt", "lv", "mt", "nl", "no", "pl", "pt", "ro",
    "ru", "sk", "sl", "sv", "tr", "uk", "is", "cy", "lb", "ca", "gl",
    "eu", "sr", "mk", "sq", "bs", "be"
}


_PROPOSE_COPY: Dict[str, Dict[str, str]] = {
    "en": {
        "subject": "SoulTribe meetup proposed by {proposer}",
        "intro": "Hi {recipient},",
        "body": "{proposer} proposed a new SoulTribe meetup.",
        "proposed_time_utc": "Proposed time (UTC)",
        "proposed_time_local": "Your time ({tz})",
        "cta_html": "Open your SoulTribe dashboard",
        "cta_text": "Visit your dashboard to confirm or suggest a different time",
    },
    "bg": {
        "subject": "Предложена среща в SoulTribe от {proposer}",
        "intro": "Здравей {recipient},",
        "body": "{proposer} предложи нова среща в SoulTribe.",
        "proposed_time_utc": "Предложено време (UTC)",
        "proposed_time_local": "Твоето време ({tz})",
        "cta_html": "Отвори таблото си в SoulTribe",
        "cta_text": "Посети таблото си, за да потвърдиш или предложиш друго време",
    },
    "cs": {
        "subject": "Setkání SoulTribe navrhl(a) {proposer}",
        "intro": "Ahoj {recipient},",
        "body": "{proposer} navrhl(a) nové setkání SoulTribe.",
        "proposed_time_utc": "Navržený čas (UTC)",
        "proposed_time_local": "Tvůj čas ({tz})",
        "cta_html": "Otevři svůj SoulTribe panel",
        "cta_text": "Navštiv panel a potvrď nebo navrhni jiný čas",
    },
    "da": {
        "subject": "SoulTribe-møde foreslået af {proposer}",
        "intro": "Hej {recipient},",
        "body": "{proposer} har foreslået et nyt SoulTribe-møde.",
        "proposed_time_utc": "Foreslået tidspunkt (UTC)",
        "proposed_time_local": "Din tid ({tz})",
        "cta_html": "Åbn dit SoulTribe-dashboard",
        "cta_text": "Besøg dit dashboard for at bekræfte eller foreslå et andet tidspunkt",
    },
    "de": {
        "subject": "SoulTribe-Treffen vorgeschlagen von {proposer}",
        "intro": "Hallo {recipient},",
        "body": "{proposer} hat ein neues SoulTribe-Treffen vorgeschlagen.",
        "proposed_time_utc": "Vorgeschlagene Zeit (UTC)",
        "proposed_time_local": "Deine Zeit ({tz})",
        "cta_html": "SoulTribe-Dashboard öffnen",
        "cta_text": "Öffne dein Dashboard, um die Zeit zu bestätigen oder eine Alternative vorzuschlagen",
    },
    "el": {
        "subject": "Συνάντηση SoulTribe προτάθηκε από τον/την {proposer}",
        "intro": "Γεια σου {recipient},",
        "body": "Ο/Η {proposer} πρότεινε μια νέα συνάντηση SoulTribe.",
        "proposed_time_utc": "Προτεινόμενη ώρα (UTC)",
        "proposed_time_local": "Η ώρα σου ({tz})",
        "cta_html": "Άνοιξε τον πίνακα ελέγχου σου στο SoulTribe",
        "cta_text": "Επισκέψου τον πίνακα ελέγχου για να επιβεβαιώσεις ή να προτείνεις διαφορετική ώρα",
    },
    "es": {
        "subject": "Reunión de SoulTribe propuesta por {proposer}",
        "intro": "Hola {recipient},",
        "body": "{proposer} propuso una nueva reunión de SoulTribe.",
        "proposed_time_utc": "Hora propuesta (UTC)",
        "proposed_time_local": "Tu horario ({tz})",
        "cta_html": "Abrir tu panel de SoulTribe",
        "cta_text": "Visita tu panel para confirmar o proponer otro horario",
    },
    "et": {
        "subject": "SoulTribe’i kohtumise pakkus {proposer}",
        "intro": "Tere {recipient},",
        "body": "{proposer} pakkus uue SoulTribe’i kohtumise.",
        "proposed_time_utc": "Pakutud aeg (UTC)",
        "proposed_time_local": "Sinu aeg ({tz})",
        "cta_html": "Ava oma SoulTribe juhtpaneel",
        "cta_text": "Külasta juhtpaneeli, et kinnitada või pakkuda muud aega",
    },
    "fi": {
        "subject": "SoulTribe-tapaaminen ehdotettu: {proposer}",
        "intro": "Hei {recipient},",
        "body": "{proposer} ehdotti uutta SoulTribe-tapaamista.",
        "proposed_time_utc": "Ehdotettu aika (UTC)",
        "proposed_time_local": "Sinun aikasi ({tz})",
        "cta_html": "Avaa SoulTribe-hallintapaneelisi",
        "cta_text": "Vieraile hallintapaneelissa vahvistaaksesi tai ehdottaaksesi toista aikaa",
    },
    "fr": {
        "subject": "Rencontre SoulTribe proposée par {proposer}",
        "intro": "Salut {recipient},",
        "body": "{proposer} a proposé une nouvelle rencontre SoulTribe.",
        "proposed_time_utc": "Heure proposée (UTC)",
        "proposed_time_local": "Ton horaire ({tz})",
        "cta_html": "Ouvre ton tableau de bord SoulTribe",
        "cta_text": "Rends-toi sur ton tableau de bord pour confirmer ou proposer un autre créneau",
    },
    "ga": {
        "subject": "Cruinniú SoulTribe molta ag {proposer}",
        "intro": "A {recipient},",
        "body": "Mhol {proposer} cruinniú nua SoulTribe.",
        "proposed_time_utc": "Am molta (UTC)",
        "proposed_time_local": "Do chuid ama ({tz})",
        "cta_html": "Oscail do phainéal SoulTribe",
        "cta_text": "Tabhair cuairt ar do phainéal chun dearbhú nó am eile a mholadh",
    },
    "hr": {
        "subject": "SoulTribe susret predložio/la {proposer}",
        "intro": "Bok {recipient},",
        "body": "{proposer} je predložio/la novi SoulTribe susret.",
        "proposed_time_utc": "Predloženo vrijeme (UTC)",
        "proposed_time_local": "Tvoje vrijeme ({tz})",
        "cta_html": "Otvori svoj SoulTribe nadzornu ploču",
        "cta_text": "Posjeti nadzornu ploču kako bi potvrdio/la ili predložio/la drugo vrijeme",
    },
    "hu": {
        "subject": "A(z) {proposer} SoulTribe-találkozót javasolt",
        "intro": "Szia {recipient},",
        "body": "{proposer} egy új SoulTribe-találkozót javasolt.",
        "proposed_time_utc": "Javasolt idő (UTC)",
        "proposed_time_local": "A te időd ({tz})",
        "cta_html": "Nyisd meg a SoulTribe vezérlőpultodat",
        "cta_text": "Látogasd meg a vezérlőpultot, hogy megerősítsd vagy más időpontot javasolj",
    },
    "it": {
        "subject": "Incontro SoulTribe proposto da {proposer}",
        "intro": "Ciao {recipient},",
        "body": "{proposer} ha proposto un nuovo incontro SoulTribe.",
        "proposed_time_utc": "Orario proposto (UTC)",
        "proposed_time_local": "Il tuo orario ({tz})",
        "cta_html": "Apri il tuo pannello SoulTribe",
        "cta_text": "Visita il pannello per confermare o proporre un orario diverso",
    },
    "lt": {
        "subject": "{proposer} pasiūlė SoulTribe susitikimą",
        "intro": "Sveikas {recipient},",
        "body": "{proposer} pasiūlė naują SoulTribe susitikimą.",
        "proposed_time_utc": "Pasiūlytas laikas (UTC)",
        "proposed_time_local": "Tavo laikas ({tz})",
        "cta_html": "Atverk savo SoulTribe valdymo skydą",
        "cta_text": "Apsilankyk valdymo skyde, kad patvirtintum ar pasiūlytum kitą laiką",
    },
    "lv": {
        "subject": "SoulTribe tikšanos ierosināja {proposer}",
        "intro": "Sveiks {recipient},",
        "body": "{proposer} ierosināja jaunu SoulTribe tikšanos.",
        "proposed_time_utc": "Ierosinātais laiks (UTC)",
        "proposed_time_local": "Tavs laiks ({tz})",
        "cta_html": "Atver savu SoulTribe informācijas paneli",
        "cta_text": "Apmeklē paneli, lai apstiprinātu vai ierosinātu citu laiku",
    },
    "mt": {
        "subject": "Laqgħa SoulTribe proposta minn {proposer}",
        "intro": "Ħelow {recipient},",
        "body": "{proposer} ippropona laqgħa ġdida ta' SoulTribe.",
        "proposed_time_utc": "Ħin propost (UTC)",
        "proposed_time_local": "Il-ħin tiegħek ({tz})",
        "cta_html": "Iftaħ id-dashboard tiegħek ta' SoulTribe",
        "cta_text": "Żur id-dashboard biex tikkonferma jew tipproponi ħin ieħor",
    },
    "nl": {
        "subject": "SoulTribe-bijeenkomst voorgesteld door {proposer}",
        "intro": "Hoi {recipient},",
        "body": "{proposer} heeft een nieuwe SoulTribe-bijeenkomst voorgesteld.",
        "proposed_time_utc": "Voorgestelde tijd (UTC)",
        "proposed_time_local": "Jouw tijd ({tz})",
        "cta_html": "Open je SoulTribe-dashboard",
        "cta_text": "Ga naar je dashboard om te bevestigen of een ander tijdstip voor te stellen",
    },
    "no": {
        "subject": "SoulTribe-møte foreslått av {proposer}",
        "intro": "Hei {recipient},",
        "body": "{proposer} har foreslått et nytt SoulTribe-møte.",
        "proposed_time_utc": "Foreslått tid (UTC)",
        "proposed_time_local": "Din tid ({tz})",
        "cta_html": "Åpne SoulTribe-kontrollpanelet ditt",
        "cta_text": "Gå til kontrollpanelet for å bekrefte eller foreslå et annet tidspunkt",
    },
    "pl": {
        "subject": "Spotkanie SoulTribe zaproponowane przez {proposer}",
        "intro": "Cześć {recipient},",
        "body": "{proposer} zaproponował(a) nowe spotkanie SoulTribe.",
        "proposed_time_utc": "Proponowany czas (UTC)",
        "proposed_time_local": "Twój czas ({tz})",
        "cta_html": "Otwórz swój panel SoulTribe",
        "cta_text": "Wejdź do panelu, aby potwierdzić lub zaproponować inny termin",
    },
    "pt": {
        "subject": "Encontro SoulTribe proposto por {proposer}",
        "intro": "Olá {recipient},",
        "body": "{proposer} propôs um novo encontro SoulTribe.",
        "proposed_time_utc": "Hora proposta (UTC)",
        "proposed_time_local": "O teu horário ({tz})",
        "cta_html": "Abre o teu painel SoulTribe",
        "cta_text": "Visita o painel para confirmar ou sugerir outro horário",
    },
    "ro": {
        "subject": "Întâlnire SoulTribe propusă de {proposer}",
        "intro": "Salut {recipient},",
        "body": "{proposer} a propus o nouă întâlnire SoulTribe.",
        "proposed_time_utc": "Ora propusă (UTC)",
        "proposed_time_local": "Ora ta ({tz})",
        "cta_html": "Deschide tabloul tău de bord SoulTribe",
        "cta_text": "Intră pe tabloul de bord pentru a confirma sau propune altă oră",
    },
    "ru": {
        "subject": "Встреча SoulTribe предложена {proposer}",
        "intro": "Привет, {recipient},",
        "body": "{proposer} предложил(а) новую встречу SoulTribe.",
        "proposed_time_utc": "Предложенное время (UTC)",
        "proposed_time_local": "Твоё время ({tz})",
        "cta_html": "Открой свою панель SoulTribe",
        "cta_text": "Перейди на панель, чтобы подтвердить или предложить другое время",
    },
    "sk": {
        "subject": "Stretnutie SoulTribe navrhol(a) {proposer}",
        "intro": "Ahoj {recipient},",
        "body": "{proposer} navrhol(a) nové stretnutie SoulTribe.",
        "proposed_time_utc": "Navrhnutý čas (UTC)",
        "proposed_time_local": "Tvoj čas ({tz})",
        "cta_html": "Otvori svoj panel SoulTribe",
        "cta_text": "Navštív panel, aby si potvrdil(a) alebo navrhol(a) iný čas",
    },
    "sl": {
        "subject": "Srečanje SoulTribe je predlagal(a) {proposer}",
        "intro": "Živjo {recipient},",
        "body": "{proposer} je predlagal(a) novo srečanje SoulTribe.",
        "proposed_time_utc": "Predlagani čas (UTC)",
        "proposed_time_local": "Tvoj čas ({tz})",
        "cta_html": "Odpri svojo SoulTribe nadzorno ploščo",
        "cta_text": "Obišči nadzorno ploščo, da potrdiš ali predlagaš drug čas",
    },
    "sv": {
        "subject": "SoulTribe-möte föreslaget av {proposer}",
        "intro": "Hej {recipient},",
        "body": "{proposer} har föreslagit ett nytt SoulTribe-möte.",
        "proposed_time_utc": "Föreslagen tid (UTC)",
        "proposed_time_local": "Din tid ({tz})",
        "cta_html": "Öppna din SoulTribe-panel",
        "cta_text": "Gå till din panel för att bekräfta eller föreslå en annan tid",
    },
    "tr": {
        "subject": "{proposer} yeni bir SoulTribe buluşması önerdi",
        "intro": "Merhaba {recipient},",
        "body": "{proposer} yeni bir SoulTribe buluşması önerdi.",
        "proposed_time_utc": "Önerilen saat (UTC)",
        "proposed_time_local": "Senin saat dilimin ({tz})",
        "cta_html": "SoulTribe kontrol panelini aç",
        "cta_text": "Kontrol paneline gidip onayla veya farklı bir zaman öner",
    },
    "uk": {
        "subject": "Зустріч SoulTribe запропонована {proposer}",
        "intro": "Привіт, {recipient},",
        "body": "{proposer} запропонував(ла) нову зустріч SoulTribe.",
        "proposed_time_utc": "Запропонований час (UTC)",
        "proposed_time_local": "Твій час ({tz})",
        "cta_html": "Відкрий свою панель SoulTribe",
        "cta_text": "Зайди на панель, щоб підтвердити або запропонувати інший час",
    },
    "is": {
        "subject": "SoulTribe fundi lagði {proposer} til",
        "intro": "Hæ {recipient},",
        "body": "{proposer} lagði til nýjan SoulTribe fund.",
        "proposed_time_utc": "Tillaga um tíma (UTC)",
        "proposed_time_local": "Þinn tími ({tz})",
        "cta_html": "Opnaðu SoulTribe-stjórnborðið þitt",
        "cta_text": "Farðu á stjórnborðið til að staðfesta eða leggja til annan tíma",
    },
    "cy": {
        "subject": "Cyfarfod SoulTribe wedi'i gynnig gan {proposer}",
        "intro": "Helo {recipient},",
        "body": "Cynigiodd {proposer} gyfarfod SoulTribe newydd.",
        "proposed_time_utc": "Amser arfaethedig (UTC)",
        "proposed_time_local": "Eich amser ({tz})",
        "cta_html": "Agor eich dangosfwrdd SoulTribe",
        "cta_text": "Ewch i'ch dangosfwrdd i gadarnhau neu awgrymu amser gwahanol",
    },
    "lb": {
        "subject": "SoulTribe-Treffen virgeschloen vum {proposer}",
        "intro": "Moien {recipient},",
        "body": "{proposer} huet en neit SoulTribe-Treffen virgeschloen.",
        "proposed_time_utc": "Virgeschloene Zäit (UTC)",
        "proposed_time_local": "Deng Zäit ({tz})",
        "cta_html": "Maach däi SoulTribe-Dashboard op",
        "cta_text": "Géi op däi Dashboard fir de Rendez-vous ze confirméieren oder eng aner Zäit virzeschloen",
    },
    "ca": {
        "subject": "Trobada SoulTribe proposada per {proposer}",
        "intro": "Hola {recipient},",
        "body": "{proposer} ha proposat una nova trobada SoulTribe.",
        "proposed_time_utc": "Hora proposada (UTC)",
        "proposed_time_local": "La teva hora ({tz})",
        "cta_html": "Obre el teu tauler SoulTribe",
        "cta_text": "Ves al teu tauler per confirmar o suggerir una altra hora",
    },
    "gl": {
        "subject": "Encontro SoulTribe proposto por {proposer}",
        "intro": "Ola {recipient},",
        "body": "{proposer} propuxo un novo encontro de SoulTribe.",
        "proposed_time_utc": "Hora proposta (UTC)",
        "proposed_time_local": "A túa hora ({tz})",
        "cta_html": "Abre o teu panel de SoulTribe",
        "cta_text": "Visita o panel para confirmar ou suxerir outra hora",
    },
    "eu": {
        "subject": "SoulTribe topaketa {proposer}-ek proposatua",
        "intro": "Kaixo {recipient},",
        "body": "{proposer}-ek SoulTribe topaketa berri bat proposatu du.",
        "proposed_time_utc": "Proposatutako ordua (UTC)",
        "proposed_time_local": "Zure ordua ({tz})",
        "cta_html": "Ireki zure SoulTribe aginte-panela",
        "cta_text": "Joan aginte-panelera ordua baieztatzeko edo beste bat proposatzeko",
    },
    "sr": {
        "subject": "SoulTribe susret предложио/ла {proposer}",
        "intro": "Ћао {recipient},",
        "body": "{proposer} је предложио/ла нови SoulTribe сусрет.",
        "proposed_time_utc": "Предложено време (UTC)",
        "proposed_time_local": "Твоје време ({tz})",
        "cta_html": "Отвори свој SoulTribe контролни панел",
        "cta_text": "Посети контролни панел да потврдиш или предложиш друго време",
    },
    "mk": {
        "subject": "SoulTribe средба предложена од {proposer}",
        "intro": "Здраво {recipient},",
        "body": "{proposer} предложи нова SoulTribe средба.",
        "proposed_time_utc": "Предложено време (UTC)",
        "proposed_time_local": "Твоето време ({tz})",
        "cta_html": "Отвори ја твојата SoulTribe контролна табла",
        "cta_text": "Посети ја контролната табла за да потврдиш или предложиш друго време",
    },
    "sq": {
        "subject": "Takim SoulTribe i propozuar nga {proposer}",
        "intro": "Përshëndetje {recipient},",
        "body": "{proposer} propozoi një takim të ri SoulTribe.",
        "proposed_time_utc": "Koha e propozuar (UTC)",
        "proposed_time_local": "Koha jote ({tz})",
        "cta_html": "Hap panelin tënd të SoulTribe",
        "cta_text": "Shko te paneli për të konfirmuar ose propozuar një orë tjetër",
    },
    "bs": {
        "subject": "SoulTribe susret predložio/la {proposer}",
        "intro": "Zdravo {recipient},",
        "body": "{proposer} je predložio/la novi SoulTribe susret.",
        "proposed_time_utc": "Predloženo vrijeme (UTC)",
        "proposed_time_local": "Tvoje vrijeme ({tz})",
        "cta_html": "Otvori svoj SoulTribe nadzorni panel",
        "cta_text": "Posjeti panel kako bi potvrdio/la ili predložio/la drugo vrijeme",
    },
    "be": {
        "subject": "Сустрэчу SoulTribe прапанаваў(ла) {proposer}",
        "intro": "Вітаем, {recipient},",
        "body": "{proposer} прапанаваў(ла) новую сустрэчу SoulTribe.",
        "proposed_time_utc": "Прапановы час (UTC)",
        "proposed_time_local": "Твой час ({tz})",
        "cta_html": "Адкрый сваю панэль SoulTribe",
        "cta_text": "Зайдзі на панэль, каб пацвердзіць або прапанаваць іншы час",
    },
}


_CONFIRM_COPY: Dict[str, Dict[str, str]] = {
    "en": {
        "subject": "SoulTribe meetup confirmed",
        "intro_html": "Hi {recipient},",
        "intro_text": "Hi {recipient},",
        "meetup_confirmed_html": "Your SoulTribe meetup is confirmed for <strong>{time}</strong>.",
        "meetup_confirmed_text": "Your SoulTribe meetup is confirmed for {time}.",
        "join_label": "Join link",
        "manage_hint_html": "You can manage the meetup from your dashboard if plans change.",
        "manage_hint_text": "You can manage the meetup from your dashboard if plans change.",
    },
    "bg": {
        "subject": "Потвърдена среща в SoulTribe",
        "intro_html": "Здравей {recipient},",
        "intro_text": "Здравей {recipient},",
        "meetup_confirmed_html": "Твоята среща SoulTribe е потвърдена за <strong>{time}</strong>.",
        "meetup_confirmed_text": "Твоята среща SoulTribe е потвърдена за {time}.",
        "join_label": "Линк за присъединяване",
        "manage_hint_html": "Можеш да управляваш срещата от таблото си, ако плановете се променят.",
        "manage_hint_text": "Можеш да управляваш срещата от таблото си, ако плановете се променят.",
    },
    "cs": {
        "subject": "Setkání SoulTribe potvrzeno",
        "intro_html": "Ahoj {recipient},",
        "intro_text": "Ahoj {recipient},",
        "meetup_confirmed_html": "Tvé setkání SoulTribe je potvrzeno na <strong>{time}</strong>.",
        "meetup_confirmed_text": "Tvé setkání SoulTribe je potvrzeno na {time}.",
        "join_label": "Odkaz na připojení",
        "manage_hint_html": "Setkání můžeš spravovat na panelu, pokud se plány změní.",
        "manage_hint_text": "Setkání můžeš spravovat na panelu, pokud se plány změní.",
    },
    "da": {
        "subject": "SoulTribe-møde bekræftet",
        "intro_html": "Hej {recipient},",
        "intro_text": "Hej {recipient},",
        "meetup_confirmed_html": "Dit SoulTribe-møde er bekræftet til <strong>{time}</strong>.",
        "meetup_confirmed_text": "Dit SoulTribe-møde er bekræftet til {time}.",
        "join_label": "Deltagerlink",
        "manage_hint_html": "Du kan administrere mødet fra dit dashboard, hvis planerne ændrer sig.",
        "manage_hint_text": "Du kan administrere mødet fra dit dashboard, hvis planerne ændrer sig.",
    },
    "de": {
        "subject": "SoulTribe-Treffen bestätigt",
        "intro_html": "Hallo {recipient},",
        "intro_text": "Hallo {recipient},",
        "meetup_confirmed_html": "Dein SoulTribe-Treffen ist für <strong>{time}</strong> bestätigt.",
        "meetup_confirmed_text": "Dein SoulTribe-Treffen ist für {time} bestätigt.",
        "join_label": "Teilnahmelink",
        "manage_hint_html": "Du kannst das Treffen im Dashboard verwalten, falls sich etwas ändert.",
        "manage_hint_text": "Du kannst das Treffen im Dashboard verwalten, falls sich etwas ändert.",
    },
    "el": {
        "subject": "Επιβεβαιώθηκε η συνάντηση SoulTribe",
        "intro_html": "Γεια σου {recipient},",
        "intro_text": "Γεια σου {recipient},",
        "meetup_confirmed_html": "Η συνάντηση SoulTribe σου επιβεβαιώθηκε για <strong>{time}</strong>.",
        "meetup_confirmed_text": "Η συνάντηση SoulTribe σου επιβεβαιώθηκε για {time}.",
        "join_label": "Σύνδεσμος συμμετοχής",
        "manage_hint_html": "Μπορείς να διαχειριστείς τη συνάντηση από τον πίνακα αν αλλάξουν τα σχέδια.",
        "manage_hint_text": "Μπορείς να διαχειριστείς τη συνάντηση από τον πίνακα αν αλλάξουν τα σχέδια.",
    },
    "es": {
        "subject": "Reunión de SoulTribe confirmada",
        "intro_html": "Hola {recipient},",
        "intro_text": "Hola {recipient},",
        "meetup_confirmed_html": "Tu reunión de SoulTribe está confirmada para <strong>{time}</strong>.",
        "meetup_confirmed_text": "Tu reunión de SoulTribe está confirmada para {time}.",
        "join_label": "Enlace de acceso",
        "manage_hint_html": "Puedes gestionar la reunión desde tu panel si cambia algo.",
        "manage_hint_text": "Puedes gestionar la reunión desde tu panel si cambia algo.",
    },
    "et": {
        "subject": "SoulTribe’i kohtumine kinnitatud",
        "intro_html": "Tere {recipient},",
        "intro_text": "Tere {recipient},",
        "meetup_confirmed_html": "Sinu SoulTribe’i kohtumine on kinnitatud ajaks <strong>{time}</strong>.",
        "meetup_confirmed_text": "Sinu SoulTribe’i kohtumine on kinnitatud ajaks {time}.",
        "join_label": "Liitumislink",
        "manage_hint_html": "Kohtumist saad hallata juhtpaneelist, kui plaanid muutuvad.",
        "manage_hint_text": "Kohtumist saad hallata juhtpaneelist, kui plaanid muutuvad.",
    },
    "fi": {
        "subject": "SoulTribe-tapaaminen vahvistettu",
        "intro_html": "Hei {recipient},",
        "intro_text": "Hei {recipient},",
        "meetup_confirmed_html": "SoulTribe-tapaamisesi on vahvistettu ajalle <strong>{time}</strong>.",
        "meetup_confirmed_text": "SoulTribe-tapaamisesi on vahvistettu ajalle {time}.",
        "join_label": "Liittymislinkki",
        "manage_hint_html": "Voit hallita tapaamista hallintapaneelista, jos suunnitelmat muuttuvat.",
        "manage_hint_text": "Voit hallita tapaamista hallintapaneelista, jos suunnitelmat muuttuvat.",
    },
    "fr": {
        "subject": "Rencontre SoulTribe confirmée",
        "intro_html": "Salut {recipient},",
        "intro_text": "Salut {recipient},",
        "meetup_confirmed_html": "Ta rencontre SoulTribe est confirmée pour <strong>{time}</strong>.",
        "meetup_confirmed_text": "Ta rencontre SoulTribe est confirmée pour {time}.",
        "join_label": "Lien de participation",
        "manage_hint_html": "Tu peux gérer la rencontre depuis ton tableau de bord si les plans changent.",
        "manage_hint_text": "Tu peux gérer la rencontre depuis ton tableau de bord si les plans changent.",
    },
    "ga": {
        "subject": "Cruinniú SoulTribe deimhnithe",
        "intro_html": "A {recipient},",
        "intro_text": "A {recipient},",
        "meetup_confirmed_html": "Tá do chruinniú SoulTribe dearbhaithe do <strong>{time}</strong>.",
        "meetup_confirmed_text": "Tá do chruinniú SoulTribe dearbhaithe do {time}.",
        "join_label": "Nasc isteach",
        "manage_hint_html": "Is féidir leat an cruinniú a bhainistiú ón bpainéal má athraíonn pleananna.",
        "manage_hint_text": "Is féidir leat an cruinniú a bhainistiú ón bpainéal má athraíonn pleananna.",
    },
    "hr": {
        "subject": "SoulTribe susret je potvrđen",
        "intro_html": "Bok {recipient},",
        "intro_text": "Bok {recipient},",
        "meetup_confirmed_html": "Tvoj SoulTribe susret potvrđen je za <strong>{time}</strong>.",
        "meetup_confirmed_text": "Tvoj SoulTribe susret potvrđen je za {time}.",
        "join_label": "Link za pridruživanje",
        "manage_hint_html": "Možeš upravljati susretom na nadzornoj ploči ako se planovi promijene.",
        "manage_hint_text": "Možeš upravljati susretom na nadzornoj ploči ako se planovi promijene.",
    },
    "hu": {
        "subject": "SoulTribe-találkozó megerősítve",
        "intro_html": "Szia {recipient},",
        "intro_text": "Szia {recipient},",
        "meetup_confirmed_html": "A SoulTribe-találkozód <strong>{time}</strong> időpontra lett megerősítve.",
        "meetup_confirmed_text": "A SoulTribe-találkozód {time} időpontra lett megerősítve.",
        "join_label": "Csatlakozási link",
        "manage_hint_html": "A találkozót a vezérlőpulton kezelheted, ha változnak a tervek.",
        "manage_hint_text": "A találkozót a vezérlőpulton kezelheted, ha változnak a tervek.",
    },
    "it": {
        "subject": "Incontro SoulTribe confermato",
        "intro_html": "Ciao {recipient},",
        "intro_text": "Ciao {recipient},",
        "meetup_confirmed_html": "Il tuo incontro SoulTribe è confermato per <strong>{time}</strong>.",
        "meetup_confirmed_text": "Il tuo incontro SoulTribe è confermato per {time}.",
        "join_label": "Link di accesso",
        "manage_hint_html": "Puoi gestire l'incontro dal tuo pannello se i piani cambiano.",
        "manage_hint_text": "Puoi gestire l'incontro dal tuo pannello se i piani cambiano.",
    },
    "lt": {
        "subject": "SoulTribe susitikimas patvirtintas",
        "intro_html": "Sveikas, {recipient},",
        "intro_text": "Sveikas, {recipient},",
        "meetup_confirmed_html": "Tavo SoulTribe susitikimas patvirtintas <strong>{time}</strong>.",
        "meetup_confirmed_text": "Tavo SoulTribe susitikimas patvirtintas {time}.",
        "join_label": "Prisijungimo nuoroda",
        "manage_hint_html": "Susitikimą gali valdyti iš valdymo skydo, jei planai pasikeis.",
        "manage_hint_text": "Susitikimą gali valdyti iš valdymo skydo, jei planai pasikeis.",
    },
    "lv": {
        "subject": "SoulTribe tikšanās apstiprināta",
        "intro_html": "Sveiks {recipient},",
        "intro_text": "Sveiks {recipient},",
        "meetup_confirmed_html": "Tava SoulTribe tikšanās ir apstiprināta uz <strong>{time}</strong>.",
        "meetup_confirmed_text": "Tava SoulTribe tikšanās ir apstiprināta uz {time}.",
        "join_label": "Pievienošanās saite",
        "manage_hint_html": "Tikšanos varēsi pārvaldīt panelī, ja plāni mainīsies.",
        "manage_hint_text": "Tikšanos varēsi pārvaldīt panelī, ja plāni mainīsies.",
    },
    "mt": {
        "subject": "Laqgħa SoulTribe ikkonfermata",
        "intro_html": "Ħelow {recipient},",
        "intro_text": "Ħelow {recipient},",
        "meetup_confirmed_html": "Il-laqgħa SoulTribe tiegħek ġiet ikkonfermata għal <strong>{time}</strong>.",
        "meetup_confirmed_text": "Il-laqgħa SoulTribe tiegħek ġiet ikkonfermata għal {time}.",
        "join_label": "Link ta' parteċipazzjoni",
        "manage_hint_html": "Tista' timmaniġġja l-laqgħa mid-dashboard jekk jinbidlu l-pjani.",
        "manage_hint_text": "Tista' timmaniġġja l-laqgħa mid-dashboard jekk jinbidlu l-pjani.",
    },
    "nl": {
        "subject": "SoulTribe-bijeenkomst bevestigd",
        "intro_html": "Hoi {recipient},",
        "intro_text": "Hoi {recipient},",
        "meetup_confirmed_html": "Je SoulTribe-bijeenkomst is bevestigd voor <strong>{time}</strong>.",
        "meetup_confirmed_text": "Je SoulTribe-bijeenkomst is bevestigd voor {time}.",
        "join_label": "Deelnamekoppeling",
        "manage_hint_html": "Je kunt de bijeenkomst beheren via je dashboard als de plannen veranderen.",
        "manage_hint_text": "Je kunt de bijeenkomst beheren via je dashboard als de plannen veranderen.",
    },
    "no": {
        "subject": "SoulTribe-møte bekreftet",
        "intro_html": "Hei {recipient},",
        "intro_text": "Hei {recipient},",
        "meetup_confirmed_html": "SoulTribe-møtet ditt er bekreftet til <strong>{time}</strong>.",
        "meetup_confirmed_text": "SoulTribe-møtet ditt er bekreftet til {time}.",
        "join_label": "Påmeldingslenke",
        "manage_hint_html": "Du kan administrere møtet fra dashbordet hvis planene endres.",
        "manage_hint_text": "Du kan administrere møtet fra dashbordet hvis planene endres.",
    },
    "pl": {
        "subject": "Spotkanie SoulTribe potwierdzone",
        "intro_html": "Cześć {recipient},",
        "intro_text": "Cześć {recipient},",
        "meetup_confirmed_html": "Twoje spotkanie SoulTribe zostało potwierdzone na <strong>{time}</strong>.",
        "meetup_confirmed_text": "Twoje spotkanie SoulTribe zostało potwierdzone na {time}.",
        "join_label": "Link do dołączenia",
        "manage_hint_html": "Możesz zarządzać spotkaniem na panelu, jeśli plany się zmienią.",
        "manage_hint_text": "Możesz zarządzać spotkaniem na panelu, jeśli plany się zmienią.",
    },
    "pt": {
        "subject": "Encontro SoulTribe confirmado",
        "intro_html": "Olá {recipient},",
        "intro_text": "Olá {recipient},",
        "meetup_confirmed_html": "O teu encontro SoulTribe está confirmado para <strong>{time}</strong>.",
        "meetup_confirmed_text": "O teu encontro SoulTribe está confirmado para {time}.",
        "join_label": "Link de participação",
        "manage_hint_html": "Podes gerir o encontro a partir do teu painel se os planos mudarem.",
        "manage_hint_text": "Podes gerir o encontro a partir do teu painel se os planos mudarem.",
    },
    "ro": {
        "subject": "Întâlnirea SoulTribe a fost confirmată",
        "intro_html": "Salut {recipient},",
        "intro_text": "Salut {recipient},",
        "meetup_confirmed_html": "Întâlnirea ta SoulTribe este confirmată pentru <strong>{time}</strong>.",
        "meetup_confirmed_text": "Întâlnirea ta SoulTribe este confirmată pentru {time}.",
        "join_label": "Link de conectare",
        "manage_hint_html": "Poți gestiona întâlnirea din panou dacă se schimbă planurile.",
        "manage_hint_text": "Poți gestiona întâlnirea din panou dacă se schimbă planurile.",
    },
    "ru": {
        "subject": "Встреча SoulTribe подтверждена",
        "intro_html": "Привет, {recipient},",
        "intro_text": "Привет, {recipient},",
        "meetup_confirmed_html": "Твоя встреча SoulTribe подтверждена на <strong>{time}</strong>.",
        "meetup_confirmed_text": "Твоя встреча SoulTribe подтверждена на {time}.",
        "join_label": "Ссылка для подключения",
        "manage_hint_html": "Можно управлять встречей через панель, если планы изменятся.",
        "manage_hint_text": "Можно управлять встречей через панель, если планы изменятся.",
    },
    "sk": {
        "subject": "Stretnutie SoulTribe je potvrdené",
        "intro_html": "Ahoj {recipient},",
        "intro_text": "Ahoj {recipient},",
        "meetup_confirmed_html": "Tvoje stretnutie SoulTribe je potvrdené na <strong>{time}</strong>.",
        "meetup_confirmed_text": "Tvoje stretnutie SoulTribe je potvrdené na {time}.",
        "join_label": "Odkaz na pripojenie",
        "manage_hint_html": "Stretnutie môžeš spravovať na paneli, ak sa plány zmenia.",
        "manage_hint_text": "Stretnutie môžeš spravovať na paneli, ak sa plány zmenia.",
    },
    "sl": {
        "subject": "SoulTribe srečanje potrjeno",
        "intro_html": "Živjo {recipient},",
        "intro_text": "Živjo {recipient},",
        "meetup_confirmed_html": "Tvoje SoulTribe srečanje je potrjeno za <strong>{time}</strong>.",
        "meetup_confirmed_text": "Tvoje SoulTribe srečanje je potrjeno za {time}.",
        "join_label": "Povezava za pridružitev",
        "manage_hint_html": "Srečanje lahko upravljaš na nadzorni plošči, če se načrti spremenijo.",
        "manage_hint_text": "Srečanje lahko upravljaš na nadzorni plošči, če se načrti spremenijo.",
    },
    "sv": {
        "subject": "SoulTribe-möte bekräftat",
        "intro_html": "Hej {recipient},",
        "intro_text": "Hej {recipient},",
        "meetup_confirmed_html": "Ditt SoulTribe-möte är bekräftat till <strong>{time}</strong>.",
        "meetup_confirmed_text": "Ditt SoulTribe-möte är bekräftat till {time}.",
        "join_label": "Anslutningslänk",
        "manage_hint_html": "Du kan hantera mötet från ditt dashboard om planerna ändras.",
        "manage_hint_text": "Du kan hantera mötet från ditt dashboard om planerna ändras.",
    },
    "tr": {
        "subject": "SoulTribe buluşması onaylandı",
        "intro_html": "Merhaba {recipient},",
        "intro_text": "Merhaba {recipient},",
        "meetup_confirmed_html": "SoulTribe buluşman <strong>{time}</strong> için onaylandı.",
        "meetup_confirmed_text": "SoulTribe buluşman {time} için onaylandı.",
        "join_label": "Katılım bağlantısı",
        "manage_hint_html": "Planlar değişirse toplantıyı kontrol panelinden yönetebilirsin.",
        "manage_hint_text": "Planlar değişirse toplantıyı kontrol panelinden yönetebilirsin.",
    },
    "uk": {
        "subject": "Зустріч SoulTribe підтверджено",
        "intro_html": "Привіт, {recipient},",
        "intro_text": "Привіт, {recipient},",
        "meetup_confirmed_html": "Твою зустріч SoulTribe підтверджено на <strong>{time}</strong>.",
        "meetup_confirmed_text": "Твою зустріч SoulTribe підтверджено на {time}.",
        "join_label": "Посилання для приєднання",
        "manage_hint_html": "Якщо плани зміняться, керуй зустріччю через панель.",
        "manage_hint_text": "Якщо плани зміняться, керуй зустріччю через панель.",
    },
    "is": {
        "subject": "SoulTribe fundur staðfestur",
        "intro_html": "Hæ {recipient},",
        "intro_text": "Hæ {recipient},",
        "meetup_confirmed_html": "SoulTribe fundurinn þinn er staðfestur fyrir <strong>{time}</strong>.",
        "meetup_confirmed_text": "SoulTribe fundurinn þinn er staðfestur fyrir {time}.",
        "join_label": "Tengill fyrir þátttöku",
        "manage_hint_html": "Þú getur stjórnað fundinum á stjórnborðinu ef áætlanir breytast.",
        "manage_hint_text": "Þú getur stjórnað fundinum á stjórnborðinu ef áætlanir breytast.",
    },
    "cy": {
        "subject": "Cyfarfod SoulTribe wedi'i gadarnhau",
        "intro_html": "Helo {recipient},",
        "intro_text": "Helo {recipient},",
        "meetup_confirmed_html": "Mae eich cyfarfod SoulTribe wedi'i gadarnhau ar gyfer <strong>{time}</strong>.",
        "meetup_confirmed_text": "Mae eich cyfarfod SoulTribe wedi'i gadarnhau ar gyfer {time}.",
        "join_label": "Dolen ymuno",
        "manage_hint_html": "Gallwch reoli'r cyfarfod o'ch dangosfwrdd os bydd cynlluniau'n newid.",
        "manage_hint_text": "Gallwch reoli'r cyfarfod o'ch dangosfwrdd os bydd cynlluniau'n newid.",
    },
    "lb": {
        "subject": "SoulTribe-Treffen confirméiert",
        "intro_html": "Moien {recipient},",
        "intro_text": "Moien {recipient},",
        "meetup_confirmed_html": "Däin SoulTribe-Treffen ass confirméiert fir <strong>{time}</strong>.",
        "meetup_confirmed_text": "Däin SoulTribe-Treffen ass confirméiert fir {time}.",
        "join_label": "Link fir matzemaachen",
        "manage_hint_html": "Du kanns den Treffen am Dashboard verwalten, wann d'Pläng sech änneren.",
        "manage_hint_text": "Du kanns den Treffen am Dashboard verwalten, wann d'Pläng sech änneren.",
    },
    "ca": {
        "subject": "Trobada SoulTribe confirmada",
        "intro_html": "Hola {recipient},",
        "intro_text": "Hola {recipient},",
        "meetup_confirmed_html": "La teva trobada SoulTribe està confirmada per a <strong>{time}</strong>.",
        "meetup_confirmed_text": "La teva trobada SoulTribe està confirmada per a {time}.",
        "join_label": "Enllaç per unir-se",
        "manage_hint_html": "Pots gestionar la trobada des del tauler si els plans canvien.",
        "manage_hint_text": "Pots gestionar la trobada des del tauler si els plans canvien.",
    },
    "gl": {
        "subject": "Encontro SoulTribe confirmado",
        "intro_html": "Ola {recipient},",
        "intro_text": "Ola {recipient},",
        "meetup_confirmed_html": "O teu encontro SoulTribe está confirmado para <strong>{time}</strong>.",
        "meetup_confirmed_text": "O teu encontro SoulTribe está confirmado para {time}.",
        "join_label": "Ligazón para unirse",
        "manage_hint_html": "Podes xestionar o encontro dende o panel se cambian os plans.",
        "manage_hint_text": "Podes xestionar o encontro dende o panel se cambian os plans.",
    },
    "eu": {
        "subject": "SoulTribe topaketa baieztatu da",
        "intro_html": "Kaixo {recipient},",
        "intro_text": "Kaixo {recipient},",
        "meetup_confirmed_html": "Zure SoulTribe topaketa <strong>{time}</strong> ordurako baieztatu da.",
        "meetup_confirmed_text": "Zure SoulTribe topaketa {time} ordurako baieztatu da.",
        "join_label": "Parte hartzeko esteka",
        "manage_hint_html": "Topaketa panela erabiliz kudeatu dezakezu, planak aldatuz gero.",
        "manage_hint_text": "Topaketa panela erabiliz kudeatu dezakezu, planak aldatuz gero.",
    },
    "sr": {
        "subject": "SoulTribe сусрет је потврђен",
        "intro_html": "Ћао {recipient},",
        "intro_text": "Ћао {recipient},",
        "meetup_confirmed_html": "Твој SoulTribe сусрет је потврђен за <strong>{time}</strong>.",
        "meetup_confirmed_text": "Твој SoulTribe сусрет је потврђен за {time}.",
        "join_label": "Линк за прикључење",
        "manage_hint_html": "Сусрет можеш управљати преко контролне табле ако се планови промене.",
        "manage_hint_text": "Сусрет можеш управљати преко контролне табле ако се планови промене.",
    },
    "mk": {
        "subject": "SoulTribe средбата е потврдена",
        "intro_html": "Здраво {recipient},",
        "intro_text": "Здраво {recipient},",
        "meetup_confirmed_html": "Твојата SoulTribe средба е потврдена за <strong>{time}</strong>.",
        "meetup_confirmed_text": "Твојата SoulTribe средба е потврдена за {time}.",
        "join_label": "Линк за приклучување",
        "manage_hint_html": "Средбата можеш да ја управуваш преку контролната табла ако се сменат плановите.",
        "manage_hint_text": "Средбата можеш да ја управуваш преку контролната табла ако се сменат плановите.",
    },
    "sq": {
        "subject": "Takimi SoulTribe u konfirmua",
        "intro_html": "Përshëndetje {recipient},",
        "intro_text": "Përshëndetje {recipient},",
        "meetup_confirmed_html": "Takimi yt SoulTribe është konfirmuar për <strong>{time}</strong>.",
        "meetup_confirmed_text": "Takimi yt SoulTribe është konfirmuar për {time}.",
        "join_label": "Lidhje pjesëmarrjeje",
        "manage_hint_html": "Mund ta menaxhosh takimin nga paneli nëse planet ndryshojnë.",
        "manage_hint_text": "Mund ta menaxhosh takimin nga paneli nëse planet ndryshojnë.",
    },
    "bs": {
        "subject": "SoulTribe susret je potvrđen",
        "intro_html": "Zdravo {recipient},",
        "intro_text": "Zdravo {recipient},",
        "meetup_confirmed_html": "Tvoj SoulTribe susret je potvrđen za <strong>{time}</strong>.",
        "meetup_confirmed_text": "Tvoj SoulTribe susret je potvrđen za {time}.",
        "join_label": "Link za pridruživanje",
        "manage_hint_html": "Susret možeš upravljati putem nadzorne ploče ako se planovi promijene.",
        "manage_hint_text": "Susret možeš upravljati putem nadzorne ploče ako se planovi promijene.",
    },
    "be": {
        "subject": "Сустрэча SoulTribe пацверджана",
        "intro_html": "Вітаем, {recipient},",
        "intro_text": "Вітаем, {recipient},",
        "meetup_confirmed_html": "Твая сустрэча SoulTribe пацверджана на <strong>{time}</strong>.",
        "meetup_confirmed_text": "Твая сустрэча SoulTribe пацверджана на {time}.",
        "join_label": "Спасылка для далучэння",
        "manage_hint_html": "Кіруй сустрэчай праз панэль, калі планы змяняюцца.",
        "manage_hint_text": "Кіруй сустрэчай праз панэль, калі планы змяняюцца.",
    },
}


def get_propose_copy(lang: str) -> Dict[str, str]:
    return _PROPOSE_COPY.get(lang, _PROPOSE_COPY["en"])


def get_confirm_copy(lang: str) -> Dict[str, str]:
    return _CONFIRM_COPY.get(lang, _CONFIRM_COPY["en"])
